create table if not exists public.editorial_posts (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  subtitle text,
  type text not null check (type in ('note', 'update', 'journal', 'essay')),
  category text not null check (category in ('inside-writon', 'building-writon', 'writing-reading', 'community', 'writon-updates')),
  status text not null default 'draft' check (status in ('idea', 'candidate', 'draft', 'review', 'approved', 'published', 'rejected', 'archived')),
  language text not null default 'en',
  author_name text not null default 'WritOn Editorial',
  author_pen_name text default 'writon_editorial',
  author_avatar_url text,
  excerpt text not null,
  content_markdown text not null,
  content_html text not null,
  estimated_read_minutes integer not null default 3 check (estimated_read_minutes >= 1),
  featured boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  source_events jsonb not null default '[]'::jsonb,
  related_posts jsonb not null default '[]'::jsonb,
  seo jsonb not null default '{}'::jsonb,
  automation_metadata jsonb not null default '{}'::jsonb
);
