FROM asia-south1-docker.pkg.dev/writon-app-2020/cloud-run-source-deploy/writon-app-api@sha256:675f82eb1bf04084bbfd051811e6887570ee5d29505c3c03ae41bec957744209

COPY feed-ranking.js /app/src/services/feed-ranking.js
COPY feed-service.js /app/src/services/feed-service.js
COPY story-quality-ranking.js /app/src/services/story-quality-ranking.js
