FROM asia-south1-docker.pkg.dev/writon-app-2020/writon/writon-api@sha256:7c66b9aad97b93e14b896e9b048121236891e89baa78393fc3e3fdb8d61b0886

COPY feed-ranking.js /app/src/services/feed-ranking.js
COPY feed-service.js /app/src/services/feed-service.js
COPY story-quality-ranking.js /app/src/services/story-quality-ranking.js
